### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ciaokitty** [SohamKukreti/omilia#29]
Create and add a brief CONTRIBUTING.md file listing all the contributing guidelines and inviting new contributors to the project.
For context and more help contact the mentors here or at our discord server

**Comment by shivangiS04** [comment]
Would love to work on this issue :)
Please assign me this issue.

Happy coding :)

**Comment by SohamKukreti** [comment]
Hi, this issue is part of [Kharagpur Winter of Code](https://kwoc.kossiitkgp.org/). If you want to participate, then be sure to check it out and apply to our project!

**Comment by shivangiS04** [comment]
Have applied through it only.

**Comment by SohamKukreti** [comment]
Alright! Please join our [discord](https://discord.gg/t6SecUAH) for further communication.
