### ISSUE TITLE
Enhance Code Clarity and Maintainability

### ISSUE THREAD

**Issue by yryuvraj** [SohamKukreti/omilia#32]
- Improve naming conventions for enhanced readability.
- Organize and restructure code for better logical grouping and overall project maintainability.

**Comment by Devansh-bit** [comment]
Hi! I'm Devansh. I would like to work on this issue.

**Comment by SohamKukreti** [comment]
Sure! I will assign this to you.

**Comment by SohamKukreti** [comment]
Great work!
